version: "3"
services:
  chat-api-service:
    build:
      context: ./chatAPI
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PWD: ${MONGO_PWD}
      MONGO_URL: ${MONGO_URL}
    labels:
      - "traefik.http.routers.chat-api.rule=Host(`s141662.devops-ap.be`) && PathPrefix(`/api`)"
      - "traefik.http.routers.chat-api.tls=true"
      - "traefik.http.routers.chat-api.tls.certresolver=letsencrypt"
    networks:
      # - backend
      - proxy
      - database

  frontend:
    image: nginx:1.22
    volumes:
      # - "./frontend/nginx.conf:/etc/nginx/nginx.conf:ro"
      # - "./frontend:/var/www/static:ro"
      - "./frontend:/usr/share/nginx/html:ro"
    labels:
      - "traefik.http.routers.chat-app.rule=Host(`s141662.devops-ap.be`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.chat-app.tls=true"
      - "traefik.http.routers.chat-app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.chat-app.entrypoints=websecure"
    networks:
      - proxy
      # - backend
      
  mongo:
    image: mongo:5.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    volumes:
      - "mongo-data:/data/db"
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
    networks:
      - database

volumes:
  mongo-data:

networks:
  proxy:
    external: true
    name: traefik
  backend:
  database: