version: "3"
services:
  todo-api-service:
    build:
      context: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=labo7
      - MYSQL_PWD=DitIsGoed!
      - MYSQL_DB=labo7
    networks:
      - backend

  frontend:
    image: nginx:1.22
    volumes:
      - "./frontend/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./frontend:/var/www/static:ro"
    labels:
      - "traefik.http.routers.todo-app.rule=Host(`s141662.devops-ap.be`)"
      - "traefik.http.routers.todo-app.tls=true"
      - "traefik.http.routers.todo-app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.todo-app.entrypoints=websecure"
    networks:
      - proxy
      - backend
  db:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=DitIsGoed!"
      - "MYSQL_DATABASE=labo7"
      - "MYSQL_USER=labo7"
      - "MYSQL_PASSWORD=DitIsGoed!"
    volumes:
      - "db-volume:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql:ro"
    networks:
      - backend

volumes:
  db-volume:

networks:
  backend:
  proxy:
    external: true
    name: traefik